
spring:
  application:
    name: various-demo

  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hcTest?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: admin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis配置
  redis:
    host: 127.0.0.1
    timeout: 3000
    password:
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  #邮件配置
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: cuawlaspaivrbgja
    username: 295836675@qq.com
    port: 587
#发件人邮箱
mail:
  fromMail:
    addr: 295836675@qq.com


server:
  servlet:
    context-path: /various-demo


#logging:
#  level:
##    com.example.variousdemo: trace
#    root: debug


#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#配置swagger配置
knife4j:
  basic:
    username: admin
    password: 123
    enable: true #开启认证
  production: false #默认是false ,屏蔽所有Swagger的相关资源
  enable: true #是否开启swagger


