
spring:
  application:
    name: various-demo

  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hcTest?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: admin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /various-demo


#logging:
#  level:
##    com.example.variousdemo: trace
#    root: debug


#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  global-config:
#    # 逻辑删除配置
#    db-config:
#      # 删除前
#      logic-not-delete-value: 1
#      # 删除后
#      logic-delete-value: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#配置swagger配置
knife4j:
  basic:
    username: admin
    password: 123
    enable: true #开启认证
  production: false #默认是false ,屏蔽所有Swagger的相关资源
  enable: true #是否开启swagger


